"""initial schema

Revision ID: 299cd84feb0c
Revises: 
Create Date: 2026-09-01 04:27:05.125447

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299cd84feb0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('de_axes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('axis1_label', sa.String(), nullable=False),
    sa.Column('axis1_var', sa.Float(), nullable=False),
    sa.Column('axis2_label', sa.String(), nullable=False),
    sa.Column('axis2_var', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('de_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('base_mean', sa.Float(), nullable=False),
    sa.Column('log2_fold_change', sa.Float(), nullable=False),
    sa.Column('lfc_se', sa.Float(), nullable=True),
    sa.Column('pvalue', sa.Float(), nullable=False),
    sa.Column('padj', sa.Float(), nullable=False),
    sa.Column('significant', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pathway_enrichment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('gene_ratio', sa.Float(), nullable=True),
    sa.Column('pvalue', sa.Float(), nullable=False),
    sa.Column('padj', sa.Float(), nullable=False),
    sa.Column('genes', sa.Text(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pca_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('pc1', sa.Float(), nullable=False),
    sa.Column('pc2', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('accession', sa.String(), nullable=False),
    sa.Column('bioproject', sa.String(), nullable=False),
    sa.Column('sra_study', sa.String(), nullable=False),
    sa.Column('organism', sa.String(), nullable=False),
    sa.Column('taxonomy_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publication', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('library_strategy', sa.String(), nullable=False),
    sa.Column('library_selection', sa.String(), nullable=False),
    sa.Column('library_layout', sa.String(), nullable=False),
    sa.Column('read_length', sa.Integer(), nullable=False),
    sa.Column('reference_genome', sa.String(), nullable=False),
    sa.Column('annotation_source', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('download_date', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('design_description', sa.Text(), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('genome_assembly', sa.String(), nullable=False),
    sa.Column('reference_release', sa.String(), nullable=False),
    sa.Column('sjdb_overhang', sa.Integer(), nullable=False),
    sa.Column('genome_sa_index_nbases', sa.Integer(), nullable=False),
    sa.Column('salmon_kmer_length', sa.Integer(), nullable=False),
    sa.Column('genome_fasta', sa.String(), nullable=False),
    sa.Column('annotation_gtf', sa.String(), nullable=False),
    sa.Column('transcriptome_fasta', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_accession'), 'projects', ['accession'], unique=True)
    op.create_table('samples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('gsm_id', sa.String(), nullable=True),
    sa.Column('donor', sa.String(), nullable=False),
    sa.Column('replicate', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('fastq1', sa.Text(), nullable=False),
    sa.Column('fastq2', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alignment_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('total_reads', sa.Integer(), nullable=False),
    sa.Column('uniquely_mapped_pct', sa.Float(), nullable=False),
    sa.Column('multi_mapped_pct', sa.Float(), nullable=False),
    sa.Column('unmapped_pct', sa.Float(), nullable=False),
    sa.Column('properly_paired_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id')
    )
    op.create_table('multiqc_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('pct_dups', sa.Float(), nullable=False),
    sa.Column('pct_gc', sa.Float(), nullable=False),
    sa.Column('mil_seqs', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id')
    )
    op.create_table('qc_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('total_reads', sa.Integer(), nullable=False),
    sa.Column('gc_percent', sa.Float(), nullable=False),
    sa.Column('q20_rate', sa.Float(), nullable=False),
    sa.Column('q30_rate', sa.Float(), nullable=False),
    sa.Column('adapter_content_pct', sa.Float(), nullable=False),
    sa.Column('duplication_pct', sa.Float(), nullable=False),
    sa.Column('retention_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_metrics_sample_id'), 'qc_metrics', ['sample_id'], unique=True)
    op.create_table('quantification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('gene_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('tpm', sa.Float(), nullable=True),
    sa.Column('counts', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quantification_sample_id'), 'quantification', ['sample_id'], unique=False)
    op.create_table('per_base_quality',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qc_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('mean_q', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['qc_id'], ['qc_metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_per_base_quality_qc_id'), 'per_base_quality', ['qc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_per_base_quality_qc_id'), table_name='per_base_quality')
    op.drop_table('per_base_quality')
    op.drop_index(op.f('ix_quantification_sample_id'), table_name='quantification')
    op.drop_table('quantification')
    op.drop_index(op.f('ix_qc_metrics_sample_id'), table_name='qc_metrics')
    op.drop_table('qc_metrics')
    op.drop_table('multiqc_summary')
    op.drop_table('alignment_stats')
    op.drop_table('samples')
    op.drop_index(op.f('ix_projects_accession'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('pca_points')
    op.drop_table('pathway_enrichment')
    op.drop_table('de_results')
    op.drop_table('de_axes')
    # ### end Alembic commands ###
