"""add execution provenance columns

Revision ID: a9f1c2d0e3b4
Revises: 299cd84feb0c
Create Date: 2026-09-09

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f1c2d0e3b4'
down_revision = '299cd84feb0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'projects',
        sa.Column('execution_real', sa.Boolean(), nullable=False,
                  server_default=sa.true()),
    )
    op.add_column(
        'projects',
        sa.Column('analysis_scope', sa.String(), nullable=False,
                  server_default='tutorial_mini_reference'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'analysis_scope')
    op.drop_column('projects', 'execution_real')
    # ### end Alembic commands ###